dist: xenial
sudo: true
language: python
python:
  - "3.8"
addons:
-  apt:
-    packages:
      - ffmpeg
      - build-dep
      - graphviz
      - libgfortran3
      - libblas-dev
      - liblapack-dev
      - gfortran      
      - libgeos-dev
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - PYTHONUNBUFFERED=True
    - SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=disk
before_install:
 - sudo apt-get install graphviz
install:
  - pip install -r requirements_conda.txt
  - pip install -r requirements.txt
  - pip install --no-deps geopandas fiona pyproj shapely
  - export PYTHONPATH=src
script:
  - python setup.py unittests
