dist: trusty
sudo: required
language: python
python:
    - "3.6"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-6 g++-6
  - sudo apt-get install libgeos-dev
  - pip install -r requirements_conda.txt
 - pip install git+https://github.com/matplotlib/basemap.git
  - pip install -r requirements.txt
  - pip install http://www.xavierdupre.fr/enseignement/setup/fr_core_news_sm-2.0.0-py3-none-any.whl
before_script:
  - python setup.py build_ext --inplace

script:
    - python setup.py unittests
