dist: focal
sudo: true
language: python
python:
    - "3.8"

before_install:
    - sudo apt-get install libgeos-dev libproj-dev proj-data graphviz libblas-dev liblapack-dev

install:
    - pip install llvmlite==0.34.0
    - pip install -r requirements_conda.txt
    - pip install -r requirements.txt
    - pip install -r requirements_geo.txt
    - pip uninstall -y shapely
    - pip install --no-binary shapely shapely
    - export PYTHONPATH=src

script:
    - python ./setup.py unittests
