image:
  - Visual Studio 2019
environment:
  matrix:
    - PYTHON: "C:\\Python39-x64"
      PYTHON_VERSION: "3.9.x"
      PYTHON_ARCH: "64"
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%" 

install:
  - "%PYTHON%\\python -m pip install --upgrade pip"
  - "%PYTHON%\\Scripts\\pip install pymyinstall"
  - "%PYTHON%\\Scripts\\pip install numpy"
  - "%PYTHON%\\Scripts\\pip install torch==1.7.1+cpu torchvision==0.8.2+cpu torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html"
  - "%PYTHON%\\Scripts\\pymy_install3 fiona cartopy pyproj gdal shapely llvmlite"
  - "%PYTHON%\\Scripts\\pip install numba --no-deps --no-warn-script-location"
  - "%PYTHON%\\Scripts\\pip install -v -r requirements_conda.txt --no-warn-script-location"
  - "%PYTHON%\\Scripts\\pip install -v -r requirements.txt --no-warn-script-location"
  - "%PYTHON%\\Scripts\\pip install -v -r requirements_geo.txt --no-warn-script-location"
  - set PYTHONPATH=src
build: off

test_script:
  - "%PYTHON%\\python -u setup.py unittests"

after_test:
  - "%PYTHON%\\python -u setup.py bdist_wheel"

artifacts:
  - path: dist
    name: papierstat
