environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%" 

install:
  - "%PYTHON%\\python -m pip install --upgrade pip"
  - "%PYTHON%\\Scripts\\pip install pymyinstall"
  - "%PYTHON%\\Scripts\\pymy_install3 --set=pyquickhelper"
  - "%PYTHON%\\Scripts\\pymy_install3 --task=tool --source=zip graphviz"
  - "%PYTHON%\\Scripts\\pymy_install3 protobuf pyshp"
  - "%PYTHON%\\Scripts\\pymy_install3 scikit-learn scipy tensorflow statsmodels xgboost"
  - "%PYTHON%\\python -c \"import locale;print('locale.getpreferredencoding=', locale.getpreferredencoding())\""
  # - "%PYTHON%\\Scripts\\pip install ftfy!=5.4.0"
  - "%PYTHON%\\Scripts\\pymy_install3 gensim ujson thinc msgpack murmurhash cytoolz xgboost wrapt regex"
  - "%PYTHON%\\Scripts\\pymy_install3 gdal fiona cartopy ujson shapely pyproj"
  - "%PYTHON%\\Scripts\\pymy_install3 spacy fr_core_news_sm"
  - "%PYTHON%\\Scripts\\pip install -r requirements_conda.txt"
  - "%PYTHON%\\Scripts\\pip install category_encoders --no-deps"
  - "%PYTHON%\\Scripts\\pip install -r requirements.txt"
  - "%PYTHON%\\Scripts\\pip install git+https://github.com/sdpython/nbconvert.git@fixes"
  - "set PATH=%PATH%;C:\\projects\\jyquickhelper\\build\\update_modules\\Graphviz\\bin"
  - set PYTHONPATH=src
build: off

test_script:
  - "%PYTHON%\\python -u setup.py unittests"

after_test:
  - "%PYTHON%\\python -u setup.py bdist_wheel"

artifacts:
  - path: dist
    name: papierstat
